// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTBU42KsfUJw00gwKx791T2fJ5Hz5z2Qk',
    appId: '1:661793489539:web:3a64c0cf75bd6922aed1b6',
    messagingSenderId: '661793489539',
    projectId: 'app-gamer-77b9f',
    authDomain: 'app-gamer-77b9f.firebaseapp.com',
    storageBucket: 'app-gamer-77b9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiX1GrWllemCr_xKzlUHXWwCOI0Cu8P1I',
    appId: '1:661793489539:android:cff53501293d2d65aed1b6',
    messagingSenderId: '661793489539',
    projectId: 'app-gamer-77b9f',
    storageBucket: 'app-gamer-77b9f.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgCWrXhrmRNOWCTwsQfGaUZZ_8hROE2OM',
    appId: '1:661793489539:ios:a27e7267dc0e042caed1b6',
    messagingSenderId: '661793489539',
    projectId: 'app-gamer-77b9f',
    storageBucket: 'app-gamer-77b9f.firebasestorage.app',
    iosBundleId: 'com.municipio.vacunacionApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgCWrXhrmRNOWCTwsQfGaUZZ_8hROE2OM',
    appId: '1:661793489539:ios:a27e7267dc0e042caed1b6',
    messagingSenderId: '661793489539',
    projectId: 'app-gamer-77b9f',
    storageBucket: 'app-gamer-77b9f.firebasestorage.app',
    iosBundleId: 'com.municipio.vacunacionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTBU42KsfUJw00gwKx791T2fJ5Hz5z2Qk',
    appId: '1:661793489539:web:8f1bc487f18844d4aed1b6',
    messagingSenderId: '661793489539',
    projectId: 'app-gamer-77b9f',
    authDomain: 'app-gamer-77b9f.firebaseapp.com',
    storageBucket: 'app-gamer-77b9f.firebasestorage.app',
  );
}
